#!/bin/bash

action=$1
shift

function usage(){
  echo "  Edit line:"
  echo "    edit ITEM#"
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

line=$1
if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    line="1"
fi
${EDITOR:-vi} +$line "$TODO_FILE"
