#!/usr/bin/env bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Add and prioritize:"
  curcmd=`basename $0`
  echo "    $curcmd A|B|C|D \"THING I NEED TO DO +project @context\""
  echo "      Add an item and prioritize it PRI in one step"
  echo "    $curcmd \"THING I NEED TO DO +project @context\""
  echo "      Add an item and prioritize it A in one step"
  echo ""
  exit
}

addpTodo() {
  priority=$1
  shift
  if "$TODO_SH" command add "$@"; then
      # figure out the line of what we just added, and prioritize it A
      line=`sed -n '$ =' "$TODO_FILE"`
      "$TODO_SH" command pri "$line" $priority
  fi
}

if [[ "$1" =~ ^[A-Z]$ ]]; then
  priority=$1
  shift
  addpTodo "$priority" "$@"
else
  addpTodo "A" "$@"
fi
