#!/bin/sh

# Reload all functions
zsh_refresh() {
  echo "Reloading all zsh functions under ${DOTDIR}/zsh/functions..."
  local f
  f=($DOTDIR/zsh/functions/*(.))
  unfunction $f:t 2> /dev/null
  autoload -U $f:t
}
