#!/usr/bin/env bash
#
# todo.sh filter to highlight todo lines
# that have been tagged with the @doding context
#
# Loop on newlines only
while IFS=$'\n' read -r line
do
  if [[ $line =~ "@now" ]]; then
    ec=${DEFAULT/"\\\\033"/"\033"}
    fg=${WHITE/"\\\\033"/"\033"}
    bg=${VIOLET_BG/"\\\\033"/"\033"}
    contexts=${VIOLET_BG/"\\\\033"/"\033"}
    # This will remove all ansi escapes
    # line=$(echo $line | sed "s,$(printf '\033')\\[[0-9;]*[a-zA-Z],,g")
    # This one will remove colors only
    line=$(echo $line | sed "s,$(printf '\033')\\[[0-9;]*m,,g")
    line="$bg$fg$line $ec"
  fi
  echo -e $line
done
